// packages/react-native/src/core.ts
import {type ComponentType, createElement} from 'react';
import {SvgXml, type XmlProps} from 'react-native-svg';

export type AwsIconProps = Omit<XmlProps, 'xml'> & {
  /** Accessible label. Without it the icon is hidden from screen readers. */
  title?: string;
};

export type AwsIconComponent = ComponentType<AwsIconProps>;

/** Factory used by the generated icon modules — not meant for direct use. */
export const createAwsIcon = (
  displayName: string,
  xml: string,
): AwsIconComponent => {
  const Component: AwsIconComponent = ({title, ...props}) =>
    createElement(SvgXml, {
      xml,
      accessible: Boolean(title),
      accessibilityLabel: title,
      width: 24,
      height: 24,
      ...props,
    });
  (Component as {displayName?: string}).displayName = displayName;
  return Component;
};

// packages/solid/src/core.tsx
import {type Component, type JSX, splitProps} from 'solid-js';

export type AwsIconProps = JSX.SvgSVGAttributes<SVGSVGElement> & {
  /** Accessible label. Without it the icon is aria-hidden (decorative). */
  title?: string;
};

export type AwsIconComponent = Component<AwsIconProps>;

/** Factory used by the generated icon modules — not meant for direct use. */
export const createAwsIcon = (
  name: string,
  attrs: Record<string, string>,
  html: string,
): AwsIconComponent => {
  const Component: AwsIconComponent = (props) => {
    const [local, rest] = splitProps(props, ['title']);
    return (
      <svg
        {...attrs}
        role="img"
        aria-hidden={local.title ? undefined : 'true'}
        aria-label={local.title}
        innerHTML={html}
        {...rest}
      />
    );
  };
  (Component as {displayName?: string}).displayName = name;
  return Component;
};
